import CoreML
import Foundation
import DesignSystem

public protocol ClassifierProtocol: Sendable {
    func classify(_ url: URL, size: Int64) async -> FileCategory
    var confidence: Double { get }
}

public final class AIClassifier: ClassifierProtocol {
    private let model: MLModel?
    private let ruleClassifier = RuleClassifier()
    public private(set) var confidence: Double = 0

    public init() {
        // Load CoreML model from bundle
        guard let modelURL = Bundle.main.url(forResource: "FileClassifier", withExtension: "mlmodelc"),
              let model = try? MLModel(contentsOf: modelURL) else {
            self.model = nil
            return
        }
        self.model = model
    }

    public func classify(_ url: URL, size: Int64) async -> FileCategory {
        guard let model = model else {
            confidence = 0.5  // Rule-based, moderate confidence
            return ruleClassifier.classify(url)
        }

        do {
            let ext = url.pathExtension
            let input = FileClassifierInput(
                fileExtension: ext,
                fileSize: Double(size),
                pathLength: Double(url.path.count)
            )
            let output = try model.prediction(from: input)
            confidence = output.featureValue(for: "confidence")?.doubleValue ?? 0.5
            let label = output.featureValue(for: "category")?.stringValue ?? "other"
            return FileCategory(rawValue: label) ?? .other
        } catch {
            confidence = 0.5
            return ruleClassifier.classify(url)
        }
    }
}

/// Generated by CoreML compiler — this is a placeholder for the actual model
/// The .mlmodel file lives in kWise/Resources/Models/
public class FileClassifierInput: MLFeatureProvider {
    public let fileExtension: String
    public let fileSize: Double
    public let pathLength: Double

    public var featureNames: Set<String> { ["fileExtension", "fileSize", "pathLength"] }

    public func featureValue(for featureName: String) -> MLFeatureValue? {
        switch featureName {
        case "fileExtension": return MLFeatureValue(string: fileExtension)
        case "fileSize": return MLFeatureValue(double: fileSize)
        case "pathLength": return MLFeatureValue(double: pathLength)
        default: return nil
        }
    }

    public init(fileExtension: String, fileSize: Double, pathLength: Double) {
        self.fileExtension = fileExtension
        self.fileSize = fileSize
        self.pathLength = pathLength
    }
}
